export const weatherIcons = [
  { keyIcon: "01d", icon: "md-sunny-outline", provider: "Ionicons" },
  { keyIcon: "02d", icon: "partly-sunny-outline", provider: "Ionicons" },
  { keyIcon: "03d", icon: "cloudy-outline", provider: "Ionicons" },
  { keyIcon: "04d", icon: "cloudy", provider: "Ionicons" },
  { keyIcon: "09d", icon: "rainy-outline", provider: "Ionicons" },
  { keyIcon: "010d", icon: "cloud-sun-rain", provider: "FontAwesome5" },
  { keyIcon: "011d", icon: "cloud-lightning", provider: "Feather" },
  { keyIcon: "013d", icon: "md-snow-outline", provider: "Ionicons" },
  { keyIcon: "050d", icon: "weather-fog", provider: "MaterialCommunityIcons" },
  { keyIcon: "01n", icon: "moon-outline", provider: "Ionicons" },
  { keyIcon: "02n", icon: "cloudy-night", provider: "Ionicons" },
  { keyIcon: "03n", icon: "cloudy-outline", provider: "Ionicons" },
  { keyIcon: "04n", icon: "cloudy", provider: "Ionicons" },
  { keyIcon: "09n", icon: "rainy", provider: "Ionicons" },
  { keyIcon: "010n", icon: "cloud-moon-rain", provider: "FontAwesome5" },
  { keyIcon: "011n", icon: "cloud-lightning", provider: "Feather" },
  { keyIcon: "013n", icon: "md-snow-outline", provider: "Ionicons" },
  { keyIcon: "050n", icon: "weather-fog", provider: "MaterialCommunityIcons" },
];
